<p></p>

<h1>Semana Nacional de Ciência e Tecnologia</h1>

<h2>Introdução a Programação em Python </h2>

# **Funções, arquivos e pacotes**

### **Funções - o que é uma função?**

Funções, em linguagens de programação, são trechos de código que podemos reutilizar em qualquer parte do código, facilitando a legibilidade e a escalabilidade. Sem funções e métodos nossos códigos seriam todos uma coisa só, e seria difícil interpretar o código como um todo, ver aonde se repetem rotinas, códigos e entre outros.

As funções também são poderosas mesmo sem haver repetição no código, pois nos permite além de dar nomes para porções específicas do código nós permite editar a funcionalidade de uma parte do código em uma parte separada no arquivo. Ou seja, não precisamos procurar aonde a função está sendo utilizada. Atualizar na função já atualiza no programa inteiro

### **Vantagens das funções**
1. Escalabilidade
2. Refatoração
3. Reutilização
4. Facilidade em editar funcionalidades no código inteiro
5. Visualização, possibilidade de dar nomes

Usamos funções no código inteiro. Todo tipo de rotina que fizermos durante o código, inclusive dentro de funções, deve ser chamado por uma função menor e mais especializada. 

Um código com poucas funções é um código mal fatorado. E um código com muitas funções, se usadas da maneira correta, é um código legível e bem fatorado.

Dica: funções devem ter nomes de verbos no imperativo, seja em inglês ou português. Isso é pois a função deve ser lida como um comando, ou seja, algo que o programador está mandando o programa fazer. Por isso, é comum evitar nomes como "somar" e usar "soma" ou "some" por exemplo.
 


In [ ]:
def some(a, b):
  # liberdade para escrever qualquer código aqui
  return a + b

In [ ]:
some(1, 2)

3

In [ ]:
1 + 2

3

# **Estrutura da função**
- **palavra chave**: `def` \\
- **nome da váriavel**: `some` \\
  *Função é uma variável chamável. Podemos passar funções por argumento.* \\
- **Parâmetros**: `a, b` \\
- **retorno**: `a + b` \\

### **Parâmetros opcionais**

É possível definir parâmetros opcionais em Python. \\

Mas qual é o uso disso? Voltando a função de soma de a e b, suponha que queremos deixar o usuário escolher printar de uma forma mais organizada o retorno da função ou apenas retornar a soma. Como fazer isso em python sem obrigar o usuário a mandar True ou False toda vez?

### **O que representa se um trecho de código pertence ou não a uma função**

Perceba que o código possui uma identação, aqui no jupyter essa indentação é de 2 espaços, nos outros editores o padrão é de 4 espaços. \\
Cada indentação, representa a entrada de um contexto. Quando você indenta para inserir um trecho de código dentro um `if`, é similar a inserir um trecho de código dentro de uma função. Então essa estrutura pode ser comparada ao trecho de código dentro de condicionais e loops.

In [ ]:
def some_print(a, b, prprint=False):
  soma = a + b

  if prprint:
    print(f'A soma de {a} e {b} é igual a {soma}')
    return
  
  return soma

In [ ]:
# outro jeito de escrever a função
def some_print(a, b, prprint=False):
  soma = a + b

  if not prprint:
    return soma
  
  print(f'A soma de {a} e {b} é igual a {soma}')  

# Perceba! Uma função sem retorno retorna None, e não necessariamente precisamos
# ter argumentos.
  

In [ ]:
# Teste 1
some_print(1, 2)

3

In [ ]:
# Teste 2
some_print(1, 2, prprint=True)

A soma de 1 e 2 é igual a 3


In [ ]:
# Teste 3
some_print(1, 2, True)

A soma de 1 e 2 é igual a 3


In [ ]:
# erro
some_print(1)

TypeError: ignored

### **O que acabou de acontecer?**

Vamos começar por analisar a estrutura da função. \\

- **`def`**: palavra chave para declarar uma função \\
- **`some_print`**: nome da variável da nova função \\
- **`a, b`**: parâmetros obrigatórios da função \\
- **`prprint`**: parâmetro opcional, diz se a função deve imprimir ou retornar a soma. \\

*Lembrem-se: um parâmetro é opcional quando o mesmo tem um valor atribuido na assinatura da função. Neste caso, prprint recebeu o valor False* \\

Repare no corpo da função: \\
1. Temos a variável soma, que armazena a soma para ser reutilizada depois \\
2. Temos uma checagem para ver qual é a decisão do programador, e ai reagimos baseado no valor de prprint. Se printamos e não retornamos nada, ou apenas retornamos. \\

Repare: podemos não retornar nada se quisermos. Afinal, em python, não precisamos declarar o retorno de uma função se não quisermos e no caso esse função pode retornar um int ou None. Nesse caso, o return foi utilizado para sair da função mais cedo.

### **Teste 1**
Apenas enviamos 1 e 2. Nesse caso, tem a mesma função da função anterior "some".

### **Teste 2 e 3**
No teste 2 mandamos o parâmetro opcional e pedimos para printar. \\
A diferença entre o teste 2 e 3 é apenas para mostrar que é possível mandar as variáveis opcionais de forma ordenada e o python aceita também.

### **Sobre o erro**
Você precisa mandar todos os parâmetros obrigatórios para a função.

### **Exemplo: fatorial**

In [ ]:
def fatorial(n):
  resultado = 1
  for i in range(1, n + 1):
    resultado = resultado * i

  return resultado

In [ ]:
fatorial(5)

120

# **Variável e escopo**

Considere o diagrama: \\
![Diagrama](https://drive.google.com/uc?id=15KihKeSr5-MOK36Gjmqii2jW5wtW7qZs) \\
Perfeito né?
Agora vamos forçar alguns erros \\
![Diagrama 2](https://drive.google.com/uc?id=1KAEHT-YGs64lzOae0yg0jvsfNliHC8QT)



### **Exemplos**

In [ ]:
var = 0

def func():
  var = 1
  print(f'Dentro de func(): var = {var}')

func()
print(f'Fora de func(): var = {var}')

Dentro de func(): var = 1
Fora de func(): var = 0


In [ ]:
var = 0

def func():
  print(f'Sou um erro! (var) {var}')
  var = 1
  print(f'Dentro de func(): var = {var}')

func()
print(f'Fora de func(): var = {var}')

UnboundLocalError: ignored

### **Podemos tirar os erros acima usando a keyword global**

Ao usar global dentro de algum escopo, você define que o escopo que a váriavel (por exemplo) x irá utilizar para leitura e escrita não é o seu escopo local, mas sim o escopo global.

In [ ]:
var = 0

def func():
  global var
  print(f'Após global: var = {var}')
  var = 1
  print(f'Dentro de func(): var = {var}')

func()
print(f'Fora de func(): var = {var}')

Após global: var = 0
Dentro de func(): var = 1
Fora de func(): var = 1


# **Algumas funções padrão do python**
Lista completa em: https://docs.python.org/3/library/functions.html

- **`help`**: mostra a documentação dado um módulo, metódo uma função
- **`max`**: encontrar o valor máximo de um vetor
- **`min`**: encontra o valor minimo de um vetor
- **`sum`**: soma todos os valores de um vetor
- **`sorted`**: ordena os valores de um vetor
- **`pow`**: o mesmo que **
- **`round`**: arredonda um valor
- **`abs`**: retorna o valor absoluto, i.e. o valor positivo equivalente de um numero.


In [ ]:
help(max)
help(sorted)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



### **Como o help obtém o texto que deve imprimir?**

In [ ]:
def exemplo():
  """
  Bem vindo a documentação da função de exemplo
  Essa função não faz nada! Mas lembre-se:
  Sua documentação precisa estar no início do corpo da função.
  """

help(exemplo)

Help on function exemplo in module __main__:

exemplo()
    Bem vindo a documentação da função de exemplo
    Essa função não faz nada! Mas lembre-se:
    Sua documentação precisa estar no início do corpo da função.



In [ ]:
vetor = [83, 97, 23, 91, 44, 85]

In [ ]:
max(vetor)

97

In [ ]:
min(vetor)

23

In [ ]:
sum(vetor)

423

In [ ]:
sorted(vetor)

[23, 44, 83, 85, 91, 97]

In [ ]:
# ordenação in place
vetor.sort()
print(vetor)

[23, 44, 83, 85, 91, 97]


In [ ]:
n = -5.2

In [ ]:
print(round(n))
print(round(5.2))
print(round(5.5))
print(round(5.535, 2))
print(round(5.535, 1))

-5
5
6
5.54
5.5


In [ ]:
print(abs(n))
print(abs(-n))

5.2
5.2


# **Abrindo e fechando arquivos**

### **`open()`**
A função `open()` recebe o caminho relativo do arquivo para abrir como argumento. \\
Ou seja, o caminho a partir de onde o terminal que o python está sendo executado está. \\
Além do caminho para o arquivo, caso o programador queira fazer algo além de simplesmente ler ele deve modificar o parâmetro opcional "mode" (que é o segundo parâmetro da função). \\
Existem os seguintes valores para mode.
1. **`'r'`** (padrão): abre um arquivo para leitura
2. **`'w'`**: Abre um arquivo para escrita, se já existir, apaga ele e começa a escrever do 0. Se não existir, o cria
4. **`'a'`**: Abre um arquivo para escrita no final. Se não existir o cria
5. **`'b'`**: Abre um arquivo binário ao invés de um arquivo de texto
7. **`'+'`**: Combinado com os modos anteriores, atualiza para o modo de atualização, isto é, leitura e escrita

Existem outros modos, mas não abordaremos eles nesse curso. Para saber mais, abra a documentação ou apenas help(open) no python.

A função retorna um objeto de arquivo.

### **`arquivo.close()`**

Ao terminar de fazer as operações com o arquivo selecionado, é necessário pedir ao sistema operacional para fechar o arquivo. Para isso, apenas use a variável retornada e chame o método `.close()` do arquivo.

### **Jeito alternativo, e melhor de se lidar com abertura de arquivos**

Ao invés de fechar um arquivo manualmente, existe um jeito em python de se fazer isso automaticamente, através da palavra chave with. Será explicada em uma celula de código.

In [ ]:
# celula para baixar os arquivos que iremos manipular
!wget -O lorem.txt "drive.google.com/uc?id=1lZp-nEm-FyWQarU6K4l9mKP3-PQicZZj&export=download"
!wget -O numeros.txt "drive.google.com/uc?id=1X8Yrmdf5nKiLkVO0-zHhiQjcxEA5qGqA&export=download"

In [ ]:
arq = open('./lorem.txt') # abre apenas para a leitura
arq.close()

arq = open('./numeros.txt', 'r+') # abre para a leitura e escrita
arq.close()

arq = open('./novo.txt', 'w') # abre apenas para a escrita
arq.close()

arq = open('./numeros.txt', 'a') # abre para escrita no final
arq.close()

In [ ]:
with open('./lorem.txt') as arq:
  print('Faça algo aqui, assim que sair do with o arquivo será fechado automaticamente')

### **Leitura de arquivos**

### **`arquivo.read()`**

Le o arquivo inteiro e armazena em uma única string

In [ ]:
with open('./lorem.txt') as arq:
  lorem_string = arq.read()

with open('./numeros.txt') as arq:
  numeros_string = arq.read()

print(lorem_string)
print(numeros_string)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus augue, fermentum vitae lectus a, commodo feugiat odio. Aliquam tincidunt convallis posuere. Nam at iaculis dolor, mattis molestie lorem. Donec odio felis, pharetra pretium velit sed, aliquet finibus lorem. Ut arcu urna, venenatis eu nulla non, rutrum dapibus est. Pellentesque nulla erat, porttitor eget odio eget, auctor cursus elit. Nulla facilisi. Nam tempus aliquet imperdiet. Mauris et dolor sodales, suscipit tortor sed, accumsan lectus. Mauris pharetra et felis scelerisque vulputate.

Suspendisse potenti. Nam nisi velit, commodo vel efficitur id, rutrum sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec malesuada viverra diam sed mollis. Vestibulum at efficitur leo. Donec sit amet imperdiet leo. Etiam a elit tempor, molestie urna non, dignissim nisl. Cras maximus l

### **`arquivo.readline()`**
Lê linha por linha do arquivo, avançando pra próxima linha

In [ ]:
with open('./lorem.txt') as arq:
  linha = arq.readline()

  while linha:
    print(linha.strip())
    linha = arq.readline()


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus augue, fermentum vitae lectus a, commodo feugiat odio. Aliquam tincidunt convallis posuere. Nam at iaculis dolor, mattis molestie lorem. Donec odio felis, pharetra pretium velit sed, aliquet finibus lorem. Ut arcu urna, venenatis eu nulla non, rutrum dapibus est. Pellentesque nulla erat, porttitor eget odio eget, auctor cursus elit. Nulla facilisi. Nam tempus aliquet imperdiet. Mauris et dolor sodales, suscipit tortor sed, accumsan lectus. Mauris pharetra et felis scelerisque vulputate.

Suspendisse potenti. Nam nisi velit, commodo vel efficitur id, rutrum sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec malesuada viverra diam sed mollis. Vestibulum at efficitur leo. Donec sit amet imperdiet leo. Etiam a elit tempor, molestie urna non, dignissim nisl. Cras maximus l

### **`arquivo.readlines()`**
Lê o arquivo inteiro, mas armazena um vetor com todas as linhas

In [ ]:
with open('./lorem.txt') as arq:
  linhas = arq.readlines()

print(linhas)
print([linha.strip() for linha in linhas])

['Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus augue, fermentum vitae lectus a, commodo feugiat odio. Aliquam tincidunt convallis posuere. Nam at iaculis dolor, mattis molestie lorem. Donec odio felis, pharetra pretium velit sed, aliquet finibus lorem. Ut arcu urna, venenatis eu nulla non, rutrum dapibus est. Pellentesque nulla erat, porttitor eget odio eget, auctor cursus elit. Nulla facilisi. Nam tempus aliquet imperdiet. Mauris et dolor sodales, suscipit tortor sed, accumsan lectus. Mauris pharetra et felis scelerisque vulputate.\n', '\n', 'Suspendisse potenti. Nam nisi velit, commodo vel efficitur id, rutrum sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec malesuada viverra diam sed mollis. Vestibulum at efficitur leo. Donec sit amet imperdiet leo. Etiam a elit tempor, molestie urna non, dignissim nisl. Cr

### **Exemplo: lendo uma tabela de números separados por espaço**

In [ ]:
with open('./numeros.txt') as arq:
  array = [[int(x) for x in line.split()] for line in arq]
  print(array)

[[53, 49, 34, 98, 21], [18, 99, 55, 78, 59], [50, 56, 43, 9, 24], [15, 54, 3, 18, 33], [89, 58, 30, 16, 5], [73, 36, 18, 88, 32], [95, 92, 66, 51, 64], [78, 2, 40, 27, 50], [14, 31, 82, 22, 85], [46, 92, 42, 49, 59], [85, 98, 60, 56, 28], [76, 96, 63, 32, 26], [81, 9, 72, 71, 91], [59, 86, 46, 50, 3], [35, 31, 57, 70, 59], [83, 68, 93, 22, 32], [40, 98, 57, 35, 39], [27, 48, 10, 40, 77], [22, 88, 88, 15, 32], [31, 55, 68, 98, 81]]


### **Escrita em arquivos**

### **`arquivo.write(string)`**

Escreve no arquivo a string enviada na função, na posição atual, que pode ser controlada através do seek

### **`arquivo.seek(offset: numero)`**

Muda a posição atual do arquivo através de um offset de bytes, que é relativo aos valores da posição. \\
Valores: \\
`0` -> Começo do arquivo \\
`1` -> Posição atual \\
`2` -> Fim do arquivo \\

### **Exemplo: escrevendo em um arquivo (truncando)**

In [ ]:
with open('./lorem.txt') as arq:
  lorem_txt = arq.read()

with open('./novo.txt', 'w+') as arq:
  arq.write(lorem_txt)
  
  arq.seek(0)
  print(arq.read())

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus augue, fermentum vitae lectus a, commodo feugiat odio. Aliquam tincidunt convallis posuere. Nam at iaculis dolor, mattis molestie lorem. Donec odio felis, pharetra pretium velit sed, aliquet finibus lorem. Ut arcu urna, venenatis eu nulla non, rutrum dapibus est. Pellentesque nulla erat, porttitor eget odio eget, auctor cursus elit. Nulla facilisi. Nam tempus aliquet imperdiet. Mauris et dolor sodales, suscipit tortor sed, accumsan lectus. Mauris pharetra et felis scelerisque vulputate.

Suspendisse potenti. Nam nisi velit, commodo vel efficitur id, rutrum sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec malesuada viverra diam sed mollis. Vestibulum at efficitur leo. Donec sit amet imperdiet leo. Etiam a elit tempor, molestie urna non, dignissim nisl. Cras maximus l

### **Exemplo: adicionando conteúdo no final do arquivo**

In [ ]:
with open('./numeros.txt') as arq:
  numeros_string = arq.read()

with open('./novo.txt', 'a+') as arq:
  arq.write(numeros_string)

  arq.seek(0)
  print(arq.read())

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus augue, fermentum vitae lectus a, commodo feugiat odio. Aliquam tincidunt convallis posuere. Nam at iaculis dolor, mattis molestie lorem. Donec odio felis, pharetra pretium velit sed, aliquet finibus lorem. Ut arcu urna, venenatis eu nulla non, rutrum dapibus est. Pellentesque nulla erat, porttitor eget odio eget, auctor cursus elit. Nulla facilisi. Nam tempus aliquet imperdiet. Mauris et dolor sodales, suscipit tortor sed, accumsan lectus. Mauris pharetra et felis scelerisque vulputate.

Suspendisse potenti. Nam nisi velit, commodo vel efficitur id, rutrum sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec malesuada viverra diam sed mollis. Vestibulum at efficitur leo. Donec sit amet imperdiet leo. Etiam a elit tempor, molestie urna non, dignissim nisl. Cras maximus l

# **Instalação de pacotes usando o `pip` e importação de módulos**

### **Instalação na sua máquina local: Windows, MacOS e Linux**
Com o python (e no linux, com o `pip` também) você possui acesso ao `pip`, que é um programa responsável por baixa e instalar os pacotes no Python.


No Windows e MacOS basta apenas utilizar `pip install <pacote>` no terminal. \\

No Linux, é necessário instalar o `pip` de forma manual. \\
> **Ubuntu**:
`sudo apt install python3-pip` \\
> **Arch Linux**:
`sudo pacman -S python-pip` \\

Após a instalação apenas rode: \\
`pip install <pacote>` \\

Exemplo: \\
`pip install numpy`

No Ubuntu, é necessário escrever `pip3` no lugar de `pip` em algumas instalações.

#### Extra - Repositórios Linux!
Em distros Linux, os pacotes do pip mais famoso estão disponíveis nos repositórios oficiais. Normalmente no formato python-\<nomedopacote\> ou python3-\<nomedopacote\> no Ubuntu. \\
Por exemplo, para instalar o numpy sem utilizar o `pip` diretamente: \\

> **Ubuntu**:
`sudo apt install python3-numpy` \\
> **Arch Linux**:
`sudo pacman -S python-numpy` \\

As vantagens de se fazer desse jeito é o melhor suporte para atualizações entre a versão do python e a versão das bibliotecas, que atualizam junto com o sistema operacional.

### **Instalação no Google Colab**
Para instalar no google colab, basta usar o `pip` direto de uma célula de código.

#### **`%pip` ou `!pip?`**
Existem duas maneiras de fazer isso, usando `%pip` ou `!pip`. Todavia, é recomendado usar o `%pip` pois ele garante que seu ambiente de desenvolvimento inteiro esteja alinhado e na mesma versão. \\
Então para instalar o numpy e o matplotlib por exemplo: \\
`%pip install numpy matplotlib`


In [ ]:
%pip install numpy matplotlib

### **Importação de pacotes**

`import`: importa um módulo, pacote ou função \\
`from`: seleciona um destino específico a partir de onde o módulo deve ser importado \\
`as`: adiciona um apelido \\

`(from) (<módulo>) import <módulo> (as) (\<apelido\>)`

In [ ]:
import random
import numpy as np
from numpy.random import rand, randint
from matplotlib import pyplot as plt

### **Exemplo: gerando um vetor de posições aleatórias com o módulo random.randint**
**randint** é uma função responsável por gerar um inteiro no intervalo [a, b]

In [ ]:
from random import randint

print([randint(0, 100) for _ in range(10)])

[73, 91, 78, 38, 73, 20, 82, 56, 42, 1]


# **NumPy**

### **O que é o NumPy?**

O NumPy é uma biblioteca feita para a linguagem Python de alta performance que adiciona suporte para trabalho com matrizes e vetores em várias dimensões.

### **O que é um array?**

Um Array do numpy é a implementação da lista do python em alta performance gerenciado pelo numpy. Ou seja, é uma sequencia de valores indexados por uma tupla de dimensão n formada por inteiros não negativos.

### **Como criar um array a partir de uma lista**

Para isso, precisamos usar a função `np.array()`, veja:


In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6]
ndarray = np.array(lista)

print(ndarray)

[1 2 3 4 5 6]


### **Outras maneiras de criar um array**

1. **`np.zeros`**: preenche um array com zeros no formato Z
2. **`np.ones`**: preenche um array com uns no formato Z
3. **`np.arange`**: preenche um array com valores de X a Y, a cada passo Z
4. **`np.linspace`**: preenche um array com Z valores de X a Y igualmente espaçados
5. **`np.random.randint`**: preenche um array com valores aleatórios de X a Y no formato Z


In [ ]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arange = np.arange(0, 10, 3)
print(arange)

[0 3 6 9]


In [ ]:
linspace = np.linspace(0, 50, 10)
print(linspace)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
randint = np.random.randint(-8, 8, (3, 3))
print(randint)

[[ 5  3  7]
 [-8  2  4]
 [ 7  6 -5]]


### **Algumas propriedades dos arrays**
1. **`ndim`**: retorna a dimensão do array
2. **`shape`**: retorna o formato do array

In [ ]:
print('Usando os campos ndim e shape para o array linspace')
print(f'Dimensão: {linspace.ndim}, formato: {linspace.shape}')
print('\nUsando np.ndim() e np.shape() para o array linspace')
print(f'Dimensão: {np.ndim(linspace)}, formato: {np.shape(linspace)}')

print('\nUsando os campos ndim e shape para o array ones')
print(f'Dimensão: {ones.ndim}, formato: {ones.shape}')

Usando os campos ndim e shape para o array linspace
Dimensão: 1, formato: (10,)

Usando np.ndim() e np.shape() para o array linspace
Dimensão: 1, formato: (10,)

Usando os campos ndim e shape para o array ones
Dimensão: 2, formato: (3, 3)


### **Algumas operações trigonométricas no NumPy**

1. **`np.pi`**: retorna o valor de pi
2. **`np.cos`**: calcula o cosseno de um número ou todos os cossenos de um array
3. **`np.sin`**: calcula o seno de um número ou todos os senos de um array
4. **`np.tan`**: calcula a tangente de um número ou todas as tangentes de um array

In [ ]:
print(f'Valor de pi: {np.pi}\n')

print(f'Valor do cosseno de 2 * pi: {np.cos(2 * np.pi)}')
print(f'Valor do seno de 2 * pi: {np.sin(2 * np.pi)}')
print(f'Valor da tangente de 2 * pi: {np.tan(2 * np.pi)}')

Valor de pi: 3.141592653589793

Valor do cosseno de 2 * pi: 1.0
Valor do seno de 2 * pi: -2.4492935982947064e-16
Valor da tangente de 2 * pi: -2.4492935982947064e-16


In [ ]:
wave = np.linspace(0, 2 * np.pi, 5)
print(f'Valores de 0, 90, 180, 270 e 360 graus em radianos: \n{wave}')

print(f'\nSenos desses valores: \n{np.sin(wave)}')
print(f'\nCossenos desses valores: \n{np.cos(wave)}')
print(f'\nTangentes desses valores: \n{np.tan(wave)}')

Valores de 0, 90, 180, 270 e 360 graus em radianos: 
[0.         1.57079633 3.14159265 4.71238898 6.28318531]

Senos desses valores: 
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]

Cossenos desses valores: 
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]

Tangentes desses valores: 
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15
 -2.44929360e-16]


### **Outras operações com arrays do NumPy**

1. **`np.sum`**: realiza a soma de todos os valores de um array
2. **`np.median`**: encontra a mediana dentro de um array
3. **`np.mean`**: encontra a média dentro de um array
4. **`np.std`**: encontra o desvio padrão dado um array
5. **`np.sort`**: ordena um array
6. **`np.abs`**: transforma um número negativo em positivo (não acontece nada se o número já for positivo) ou transforma todos os números negativos em positivos dentro de um array
7. **`np.random.shuffle`**: reordena as posições do array de forma aleatória


In [ ]:
seq = np.arange(1, 11)

print(f'Sequencia de 1 a 10: {seq}')
print(f'Soma dos numeros da sequencia: {np.sum(seq)}')
print(f'Mediana da sequência: {np.median(seq)}')
print(f'Média da sequência: {np.mean(seq)}')
print(f'Desvio padrão da sequência: {np.std(seq)}')

Sequencia de 1 a 10: [ 1  2  3  4  5  6  7  8  9 10]
Soma dos numeros da sequencia: 55
Mediana da sequência: 5.5
Média da sequência: 5.5
Desvio padrão da sequência: 2.8722813232690143


In [ ]:
np.random.shuffle(seq)
print(f'Sequência após o shuffle \n{seq}')

seq = np.sort(seq)
print(f'\nSequência após o sort \n{seq}')

Sequência após o shuffle 
[ 9  2  3  7  5  6  1  8 10  4]

Sequência após o sort 
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
randarr = np.random.randint(-10, 11, 10)
print(f'Sequência aleatória de -10 a 10 \n{randarr}')

print(f'\nApós o np.abs(): \n{np.abs(randarr)}')

Sequência aleatória de -10 a 10 
[ 9  8 -8  7  8 -8  6  4  0  1]

Após o np.abs(): 
[9 8 8 7 8 8 6 4 0 1]


### **Algumas maneiras diferentes de acessar valores de um array**

O acesso é identico a uma lista convencional


In [ ]:
print(zeros[0])
print(zeros[0][0])

[0. 0. 0.]
0.0


### **`Slice`**

É possível fazer slice de arrays assim como é possível fazer slice de listas em Python. Ou seja, `array[start:stop[:step]]`.
- **`start`**: o indice que começa o slice
- **`stop`**: o indice que termina
- **`step`**: o "passo", ou seja, de quantos em quantos indices é desejado exibir

In [ ]:
seq = np.arange(-100, 101)
print(seq)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    0    1    2    3    4    5    6    7    8    9   10   11
   12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   37   38   39
   40   41   42   43   44   45   46   47   48   49   50   51   52   53
   54   55   56   57   58   59   60   61   62   63   64   65   66   67
   68   69   70   71   72   73   74   75   76   77   78   79   80   81
   82   83   84   85   86   87   88   89   90   91   92   93   94   95
   96 

### **Exemplo: indíces que repesentam os valores pares de 0 a 100**

In [ ]:
print(seq[100:201:2])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### **Exemplo indíces que representam os valores de 50 a 100**

In [ ]:
print(seq[150:201])

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


### **Slice condicional**

Além do Slice tradicional, o numpy oferece o slice condicional. Ou seja, é enviado uma condição para realizar um slice no array, **baseado no valor
e não no índice** \\
Para isso, é necessario fazer um conjunto de condições com operadores não ambíguos (`==`, `!=`, `&` para `and`, `|` para `or`).

### **Exemplo: valor positivo é igual a 100**

In [ ]:
print(seq[abs(seq) == 100])

[-100  100]


### **Exemplo: valores diferentes de 0**

In [ ]:
print(seq[seq != 0])

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    1    2    3    4    5    6    7    8    9   10   11   12
   13   14   15   16   17   18   19   20   21   22   23   24   25   26
   27   28   29   30   31   32   33   34   35   36   37   38   39   40
   41   42   43   44   45   46   47   48   49   50   51   52   53   54
   55   56   57   58   59   60   61   62   63   64   65   66   67   68
   69   70   71   72   73   74   75   76   77   78   79   80   81   82
   83   84   85   86   87   88   89   90   91   92   93   94   95   96
   97 

### **Exemplo: valores maiores que 50**

In [ ]:
print(seq[seq > 50])

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


### **Exemplo: valores no intervalo (-inf, -50] ou [50, inf)**

In [ ]:
print(seq[(seq <= -50) | (seq >= 50)])

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50   50   51   52   53   54
   55   56   57   58   59   60   61   62   63   64   65   66   67   68
   69   70   71   72   73   74   75   76   77   78   79   80   81   82
   83   84   85   86   87   88   89   90   91   92   93   94   95   96
   97   98   99  100]


### **Exemplo: valores no intervalo [-50, 50]**

In [ ]:
print(seq[(seq >= -50) & (seq <= 50)])

[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33
 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15
 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3
   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50]


# **Operações entre arrays e arrays, e arrays e escalares**

Os operadores aritméticos no numpy fazem as operações elemento por elemento. Então `*`, `+`, `-`, `/` entre dois arrays de dimensão n irá realizar a operação elemento por elemento. O mesmo com escalares. \\
Todavia, caso queira fazer a multiplação de matrizes convencional, basta utilizar `np.dot(A, B)`


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 2, 2], [4, 4, 4], [6, 6, 6]])

In [ ]:
print(A * B)

[[ 2  4  6]
 [16 20 24]
 [42 48 54]]


In [ ]:
print(A / B)

[[0.5        1.         1.5       ]
 [1.         1.25       1.5       ]
 [1.16666667 1.33333333 1.5       ]]


In [ ]:
print(A + B)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [ ]:
print(A - B)

[[-1  0  1]
 [ 0  1  2]
 [ 1  2  3]]


In [ ]:
np.dot(A, B)

array([[ 28,  28,  28],
       [ 64,  64,  64],
       [100, 100, 100]])

In [ ]:
print(B / 2)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
print(B * 2)

[[ 4  4  4]
 [ 8  8  8]
 [12 12 12]]


In [ ]:
print(B + 2)

[[4 4 4]
 [6 6 6]
 [8 8 8]]


### **Diferença dos operador `*` para as listas**

In [ ]:
a = [1, 2, 3]
b = a * 2
print(f'(list) Após a * 2: {b}')

a = np.array(a)
b = a * 2
print(f'\n(np.ndarray) Após a * 2: {b}')

(list) Após a * 2: [1, 2, 3, 1, 2, 3]

(np.ndarray) Após a * 2: [2 4 6]


### **Reproduzindo o operador de adição do NumPy**


In [ ]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

array3 = array1 + array2
array4 = np.concatenate([array1, array2])

list1 = list(array1)
list2 = list(array2)

from operator import add
list3 = list(map(add, list1, list2))
list4 = list1 + list2

print(f'(np.ndarray) array1 + array2: {array3}',
      f'\n(np.ndarray) np.concatenate(array1, array2): {array4}')
print(f'\n(list) Equivalente da soma do NumPy usando map: {list3}',
      f'\n(list) list1 + list2: {list4}')

(np.ndarray) array1 + array2: [ 6  8 10 12] 
(np.ndarray) np.concatenate(array1, array2): [1 2 3 4 5 6 7 8]

(list) Equivalente da soma do NumPy usando map: [6, 8, 10, 12] 
(list) list1 + list2: [1, 2, 3, 4, 5, 6, 7, 8]


# **Comparativo de performance**

Comparação inspirada em: https://stackoverflow.com/questions/18713321/element-wise-addition-of-2-lists \\

In [ ]:
import timeit
from operator import add
import numpy as np

list1 = [4, 5, 6]*10**5
list2 = [1, 2, 3]*10**5

array1 = np.array(list1)
array2 = np.array(list2)

def run_map_add():
  list(map(add, list1, list2))

def run_arr_add():
  array1 + array2

print('Tempo sem NumPy (1 execução):', timeit.timeit(run_map_add, number=1))
print('Tempo com NumPy (1 execução):', timeit.timeit(run_arr_add, number=1))
print('Tempo sem NumPy (200 execuções):', timeit.timeit(run_map_add, number=200))
print('Tempo com NumPy (200 execuções):', timeit.timeit(run_arr_add, number=200))
print('Tempo com NumPy (10000 execuções):', timeit.timeit(run_arr_add, number=10000))

Tempo sem NumPy (1 execução): 0.027576686999964295
Tempo com NumPy (1 execução): 0.0014457890001722262
Tempo sem NumPy (200 execuções): 3.8005736939994677
Tempo com NumPy (200 execuções): 0.0966130440001507
Tempo com NumPy (10000 execuções): 4.352219678000438


# **Extra: como carregar um arquivo CSV usando NumPy**
É possível carregar um arquivo csv diretamente a um array do NumPy usando o `np.loadtxt()`. \\

Para isso o primeiro argumento deve ser aonde o arquivo se encontra, o segundo o delimitador (no caso do csv, é o ","), e caso tenha uma linha de descrição da tabela de dados, precisamos pular essa linha usando o skiprows=1 (ou quantas linhas forem necessárias)

In [ ]:
print(np.loadtxt('./sample_data/california_housing_train.csv', delimiter=',', skiprows=1))

[[-1.1431e+02  3.4190e+01  1.5000e+01 ...  4.7200e+02  1.4936e+00
   6.6900e+04]
 [-1.1447e+02  3.4400e+01  1.9000e+01 ...  4.6300e+02  1.8200e+00
   8.0100e+04]
 [-1.1456e+02  3.3690e+01  1.7000e+01 ...  1.1700e+02  1.6509e+00
   8.5700e+04]
 ...
 [-1.2430e+02  4.1840e+01  1.7000e+01 ...  4.5600e+02  3.0313e+00
   1.0360e+05]
 [-1.2430e+02  4.1800e+01  1.9000e+01 ...  4.7800e+02  1.9797e+00
   8.5800e+04]
 [-1.2435e+02  4.0540e+01  5.2000e+01 ...  2.7000e+02  3.0147e+00
   9.4600e+04]]


## Contato profissional e acadêmico

Github: https://github.com/orlando-oli \\
E-mail: clevio.orlando@unifesp.br

Podem enviar dúvidas!

---

# **Introdução ao Pandas**

O [Pandas](https://pandas.pydata.org) é uma biblioteca de código aberto amplamente utilizada por cientistas e analistas de dados, isso se dá pelo fato de que ela facilita a manipulação de dados tabulados (como um Excel ou tabela de banco de dados). Alguns benefícios que a biblioteca fornece são:

* Estruturas de dados e operações similares à uma planilha comum (Series e Dataframe);
* Funções prontas para processamento e "limpeza" de dados;
* Funções prontas para manipulação de diferentes tipos de arquivos (csv, xls, xlsx, json, etc)

![series_and_dataframes.png](https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png)



### **Hello World!**

A fim de termos o primeiro contato com as estruturas de dados básicas, vamos criar as séries e o dataframe exibidos na imagem ilustrativa e realizar algumas operações básicas.

Obs.: Nesse primeiro exercício também iremos realizar a importação da biblioteca.

In [ ]:
import pandas as pd # A partir de agora podemos referenciar a biblioteca do Pandas com o "pd"

Criando as duas séries com os nomes "Apples" e "Orange"

In [ ]:
apples_serie = pd.Series(data=[3,2,0,1], name='Apples')
oranges_serie = pd.Series(data=[0,3,7,2], name='Oranges')

print(apples_serie)
print(oranges_serie)

É importante notar que as séries não são simples lista.

In [ ]:
type(apples_serie)

Os operadores básicos (+, -, * e /) podem ser utilizados para operar duas séries, gerando uma nova série. Nesse caso, cada valor da primeira série é operado com o valor correspondente (mesmo índice) na segunda série.

In [ ]:
apples_serie + oranges_serie
# apples_serie - oranges_serie
# apples_serie * oranges_serie
# apples_serie / oranges_serie

Para criarmos o Dataframe podemos passar as duas séries em formato de dicionário, onde a **chave** será o nome da série (coluna) e o **valor** será a série em si.

In [ ]:
fruits_df = pd.DataFrame(data={
                        'Apples': apples_serie,
                        'Oranges': oranges_serie
                        })
fruits_df

Também podemos adicionar séries (colunas) à um dataframe de maneira bastante simples.

In [ ]:
total_fruits = apples_serie + oranges_serie
fruits_df['Total Fruits'] = total_fruits
fruits_df

## **Exercício #1**

Assumindo que cada linha do nosso dataframe (fruits_df) representa uma venda de um hortifruti (extremamente especializado em maçãs e laranjas rs). Cria duas novas colunas: i) Proporção de maças na venda e ii) Proporção de laranjas na venda.

In [ ]:
# Sua Resposta aqui
...

In [ ]:
#@title Resposta

fruits_df['Apples %'] = fruits_df['Apples']/fruits_df['Total Fruits']
fruits_df['Oranges %'] = fruits_df['Oranges']/fruits_df['Total Fruits']
fruits_df

# **Explorando um dataset**

A fim de se familiarizar um pouco mais com a estrutura do DataFrame, vamos carregar e trabalhar com um dataset mais interessante.

Todas as funções disponíveis no Pandas pode ser encontrada [aqui](https://pandas.pydata.org/docs/reference/frame.html)

Uma grande facilidade oferecida pelo Pandas é o carregamento de dados de diferentes fontes. Para exemplificar isso, além de termos algo mais interessante para trabalhar, vamos carregar uma base diretamente de uma [planilha](https://docs.google.com/spreadsheets/d/1Bq5IxppilddbsQ0aVAToRkVdeQ0i9KlEsWPLq-fCaQg/edit?usp=sharing) do Google Drive (Retirada do [Kaggle](https://www.kaggle.com/gregorut/videogamesales)).

In [ ]:
# Não se preocupe com esse trecho de código
# Ele básicamente vai cuidar da autorização de acesso e 
# de ler os dados da planilha para a varável "rows"
# ===========================================================
from google.colab import auth
import gspread
from oauth2client.client import GoogleCredentials
auth.authenticate_user()

GAMES_SALES_DATASET_URL = 'https://docs.google.com/spreadsheets/d/1Bq5IxppilddbsQ0aVAToRkVdeQ0i9KlEsWPLq-fCaQg/edit?usp=sharing'

gc = gspread.authorize(GoogleCredentials.get_application_default())
worksheet = gc.open_by_url(GAMES_SALES_DATASET_URL).sheet1
rows = worksheet.get_all_values()
# ===========================================================

# Vamos dar uma olhada nos dados que estão em "rows"
# Note que é uma simples lista de listas, onde o primeiro item é uma lista com
# os dados de cabeçalho e os demais itens são as linhas de dados
print(type(rows))
print(rows[0])
print(rows[1])
print(rows[2])

Uma vez que os dados da planilha foi carregada para a variável "rows", vamos utiliza-la para criar um DataFrame do Pandas

In [ ]:
# Podemos utilizar a função from_records() para definir as linhas e cabecalhos
g_sales_df = pd.DataFrame.from_records(columns=rows[0], data=rows[1:])

A partir desse ponto, a variável g_sales_df possui um DataFrame do Pandas com os dados obtidos da planilha referenciada. Vamos investigar um pouco esses dados utilizando algumas funções disponíveis.

In [ ]:
# A função head() pode ser utilizada visualizar apenas as primeiras linhas do
# DataFrame

g_sales_df.head() # Por default, são exibidas 5 linhas, mas podemos definir quantas queremos

In [ ]:
# A função describe() apresenta um resumo sobre os dados de cada coluna no DataFrame
# As informações apresentadas variam com o tipo de dados da coluna.

g_sales_df.describe()

In [ ]:
# Vamos dar uma olhada nos tipos de dados de cada coluna
g_sales_df.dtypes

In [ ]:
# Visando evitar esse tipo genérico (object), vamos converter as colunas
# para tipos de dados mais interessantes
g_sales_df['Rank'] = g_sales_df['Rank'].astype('int')
g_sales_df['Name'] = g_sales_df['Name'].astype('category')
g_sales_df['Platform'] = g_sales_df['Platform'].astype('category')
g_sales_df['Year'] = g_sales_df['Year'].astype('category')
g_sales_df['Genre'] = g_sales_df['Genre'].astype('category')
g_sales_df['Publisher'] = g_sales_df['Publisher'].astype('category')
g_sales_df['NA_Sales'] = g_sales_df['NA_Sales'].astype('float')
g_sales_df['EU_Sales'] = g_sales_df['EU_Sales'].astype('float')
g_sales_df['JP_Sales'] = g_sales_df['JP_Sales'].astype('float')
g_sales_df['Other_Sales'] = g_sales_df['Other_Sales'].astype('float')
g_sales_df['Global_Sales'] = g_sales_df['Global_Sales'].astype('float')
g_sales_df.dtypes

In [ ]:
g_sales_df.describe()

In [ ]:
# Para visualizarmos o resumo das colunas categóricas, vamos selecionar apenas elas
# e executar o describe novamente.
# Para selectionar colunas específicas podemos simplesmente passar os nomes das 
# colunas de interesse em uma lista

# temp_df será um DataFrame apenas com as colunas selecionadas
temp_df = g_sales_df[['Name', 'Platform', 'Year', 'Genre', 'Publisher']]
temp_df.describe()

### **Outras formas para acessar os dados**

In [ ]:
# Selecionando uma coluna específica
g_sales_df.Genre # O mesmo que g_sales_df['Genre']

In [ ]:
# Selecionando Linhas
g_sales_df[10:15] # Seleciona as linhas no intervalo [10, 15)

In [ ]:
# Selecionando as últimas linhas
g_sales_df.tail() # Similar ao head()

In [ ]:
# Selecionando linhas e colunas ao mesmo tempo
g_sales_df.iloc[0:4, 2:5] # Seleciona as linhas [0, 4) e colunas [2, 5)

# Modo alternativo
# g_sales_df.iloc[[0,1,2,3], [2,3,4]]

In [ ]:
# Acessando um único elemento (como uma matriz)
g_sales_df.iloc[402, 2] # Elemento na linha 402 e coluna 2

In [ ]:
# Selecionando com comparador lógico
g_sales_df[g_sales_df['NA_Sales'] > 15] # Selecionando apenas linhas com venda superior a 15M na North America

In [ ]:
# Selecionando com a condição 'isin'
g_sales_df[g_sales_df['Genre'].isin(['Sports', 'Puzzle'])] # Seleciona todos itens do genero Sports ou Puzzle

### **Ordenando o DataFrame**

In [ ]:
# A função sort_values ordena todo o DataFrame por uma determinada coluna
new_df = g_sales_df.sort_values(by='EU_Sales', ascending=False) # Ordenando das maiores vendas para as menores na Europa
new_df

## **Exercício #2**

Utilizando o dataset de vendas de games, encontre os nomes dos Top 5 de vendas da plataforma PS3 no Japão.

In [ ]:
# Sua Resposta aqui
...

In [ ]:
#@title Resposta

top_sales_jp = g_sales_df.sort_values(by='JP_Sales', ascending=False)
top_sales_jp_ps3 = top_sales_jp[top_sales_jp['Platform'].isin(['PS3'])]
top_sales_jp_ps3.iloc[:5, 1:2]


# **Agrupando dados**

Quando trabalhamos com os dados categóricos em uma planilha ou em um banco de dados, a realização de agrupamentos e sumariazações é bastante comum e útil. O Pandas oferece algumas alternativas para esse tipo de operação.

### **Group-By**

Operação similar à operaçã de mesmo nome utilizada na linguagem SQL para bancos de dados relacionais.

In [ ]:
# Obtendo a soma de vendas para cada plataforma
g_sales_df.groupby(by=['Platform']).sum()

In [ ]:
# Obtendo a média de vendas para cada genero
g_sales_df.groupby(by=['Genre']).mean()

In [ ]:
# Obtendo a soma de vendas para cada genero em cada ano
g_sales_df.groupby(by=['Genre', 'Year']).sum()

In [ ]:
# Extra - Podemos usar a função 'loc' para acessar os valores dos anos de um genero específico
vendas_por_gen_ano = g_sales_df.groupby(by=['Genre', 'Year']).sum()
vendas_por_gen_ano.loc['Racing'].head(10) # Apenas os 10 primeiros

### **Pivot Tables**

Formatação bastante utilizada em planilhas.

In [ ]:
# Criando uma Pivot table que irá mostras a soma das vendas na North America para cada Ano, Plataforma e Genero
# Obs.: O parâmetro fill_value, indica para a função substituir por 0 qualquer valor faltante
g_sales_df.pivot_table(values='NA_Sales', index=['Year', 'Platform'], columns=['Genre'], aggfunc='sum', fill_value=0)

## **Exercício #3**

Utilizando o dataset de vendas de games, construa uma Pivot Table que apresente a venda total na Europa para cada Ano x Genero.

In [ ]:
# Sua Resposta aqui
...

In [ ]:
#@title Resposta
g_sales_df.pivot_table(values='EU_Sales', index='Year', columns='Genre', aggfunc='sum', fill_value=0)

# **Material complementar**

[10 minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)

[Manual Completo](https://pandas.pydata.org/docs/user_guide/index.html)

[Exemplos](https://matplotlib.org/tutorials/introductory/sample_plots.html#sphx-glr-tutorials-introductory-sample-plots-py)

[API](https://matplotlib.org/api/index.html)

[Github](https://github.com/pandas-dev/pandas)

# **Introdução ao Matplotlib**

O [Matplotlib](https://matplotlib.org/) é uma biblioteca de código aberto para facilitar a contrução de gráficos e visualização de dados em geral (2D e 3D). O modo de utilizar a ferramenta é bastante semelhante à trabalhar com o Matlab ou R ([Matlab vs Python vs R](http://www.jds-online.com/files/150%E5%AE%8C%E6%88%90V.pdf)).

Exemplos de gráficos disponíveis são:

* Gráficos de Barras
* Gráficos de Linhas
* Gráficos de Dispersão (Scatter)
* Histogramas
* E **MUITOS** outros

### **Hello World!**

In [ ]:
import matplotlib.pyplot as plt # A partir de agora podemos referenciar a lib com plt

# Plot y=x^2, por default x=range(y)
plt.plot([i**2 for i in range(100)]) # O mesmo que [0, 1, 4, 9, 16, 25, ...]

# plt.show() # Caso esteja rodando fora de um notebook, esse comando desenha o gráfico na tela

In [ ]:
# Caso queira controlar o valor de x também, basta passar 2 listas

# x, y
plt.plot([1, 4, 8, 10, -5], [10, 32, -4, 17, 1]) # Sim, x e y não precisar crescer juntos

### **Componentes dos Gráficos**


![chart_components.png](https://matplotlib.org/_images/anatomy.png)

In [ ]:
# fig: É a "Figure", basicamente é imagem/figura como um todo e contém os demais elementos.
# ax: É o "Axes", onde a área de dados é desenhada.
# Importante: "Axes" != "Axis".
# Um "Axes" pode ter 2 ou 3 eixos ("Axis")
# os "Axis" cuida dos limites e ticks

fig, ax = plt.subplots()
ax.plot(range(10), label='linear')
ax.set_xlabel('x label')
ax.set_xlim(left=0, right=15)
ax.set_ylabel('y label')
ax.set_ylim(bottom=0, top=20)
ax.set_title("Gráfico Simples")
ax.legend() # Apenas faz a legenda ser exibida, os dados vem do label da curva
ax.grid() # Draw grid lines
# fig.show() Nesse caso, ao invés de plt.show() podemos chamar o show() da "Figure"

### **Customizando**

Vamor construir um gráfico de linha mais elaborado, visando explorar algumas possibilidades.

In [ ]:
fig, ax = plt.subplots()
ax.plot([i**2 for i in range(20)], linestyle='-', marker='o', color='green', linewidth=3, markersize=8)

As opções disponíveis para cada parametro são:


* **`linestyle`**: solid, dashed, dashdot, dotted, '-', '--', '-.', ':', None, ' ']
* **`marker`**: https://matplotlib.org/api/markers_api.html
* **`color`**: String representando o RGB (Ex.: '#031A8D') or o nome de uma cor disponível (https://matplotlib.org/3.1.0/gallery/color/named_colors.html).



In [ ]:
# Podemos utilizar uma única string para configurar esses 3 elementos
fig, ax = plt.subplots()
ax.plot([i**2 for i in range(20)], '--or')

## **Exercício #4**

A fim de explorar um pouco essas opções, crie um gráfico que tenha:
* Título
* Grid
* Legenda
* Uma curva customizada (quais quer valores, mas com cor e marcadores diferentes do original)


In [ ]:
# Seu código aqui
# ...

In [ ]:
#@title Resposta
import numpy as np

# Gerando os dados de uma senóide
t = np.arange(0.0, 2.0, 0.01)
x = np.sin(3 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(x, '.g', label='Seno')
ax.set_title("Um simples gráfico de Seno")
ax.legend()
ax.grid()

# **Gráficos de Barras**

[API](https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar)

In [ ]:
# Vamos plotar as vendas de 3 produtos nos quarters de 2019
quarters = ['Q1/2019', 'Q2/2019', 'Q3/2019', 'Q4/2019'] # Eixo x
vendas_pcs = [10, 13, 11, 16]
vendas_laptops = [24, 23, 27, 32]
vendas_video_games = [8, 6, 7, 10]
largura = 0.5

fig, ax = plt.subplots()
ax.bar(x=quarters, height=vendas_pcs, width=largura, label='PCs')

# Para "empilhar" uma barra, marcamos seu inicio no final da anterior com o parâmetro "bottom"
ax.bar(x=quarters, height=vendas_laptops, width=largura, bottom=vendas_pcs, label='Laptops')

# Para "empilhar" a terceirca barra, precisamos definir onde as outras últimas barras terminam
# A função zip() retorna tuplas com os valores das listas de um mesmo índice
#print(list(zip(vendas_pcs, vendas_laptops)))
temp_bottom = [a+b for a,b in zip(vendas_pcs, vendas_laptops)]
ax.bar(x=quarters, height=vendas_video_games, width=largura, bottom=temp_bottom, label='Video Games')

ax.set_ylabel('Total de Vendas')
ax.set_xlabel('Quarter')
ax.set_title('Vendas por Quarter e Produto')
ax.legend()

## **Exercício #5**

Crie um gráfico empilhado dados fictícios (ou reais) de seu interesse.

### **Gráfico de Pizza**

[API](https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.axes.Axes.pie.html#matplotlib.axes.Axes.pie)

In [ ]:
products = ['PCs', 'Laptops', 'Video Games']
vendas = [10, 24, 8]
explode = (0, 0, 0.1) # Para destacar o slice de 'Video Games' do gráfico

fig, ax = plt.subplots()

# autopct: Define o formato da proporção exibida dentro de cada fatia
# show: Aplica um pouco de sobre no gráfico
ax.pie(vendas, explode=explode, labels=products, autopct='%.2f%%', shadow=True)
fig.show()

# **Multiplos Gráficos**

### **Multiplas curvas em 1 gráfico**

In [ ]:
# Dados para plots
quarters = ['Q1/2019', 'Q2/2019', 'Q3/2019', 'Q4/2019']
vendas_pcs = [10, 13, 11, 16]
vendas_laptops = [24, 23, 27, 32]
vendas_video_games = [8, 6, 7, 10]
bottom_2 = [a+b for a,b in zip(vendas_pcs, vendas_laptops)]
lucro = [3715.76, 3910.23, 4407.53, 6131.59]
largura = 0.5

# Gerando barras
fig, ax_qtd = plt.subplots()
ax_qtd.bar(x=quarters, height=vendas_pcs, width=largura, label='PCs')
ax_qtd.bar(x=quarters, height=vendas_laptops, width=largura, bottom=vendas_pcs, label='Laptops')
ax_qtd.bar(x=quarters, height=vendas_video_games, width=largura, bottom=bottom_2, label='Video Games')

# Gerando linhas
# Gerando novo eixo y com o mesmo x
ax_lucro = ax_qtd.twinx()
ax_lucro.plot(lucro, '--om', label='Lucro', linewidth=4, markersize=8)

# Adicionando Informações no gráfico
ax_qtd.set_xlabel('Quarter')
ax_qtd.set_ylabel('Venda Total')

ax_lucro.set_ylabel('Lucro Total')
ax_lucro.set_ylim(0, 7000)

ax_qtd.set_title('Vendas por Quarter e Produto')
ax_qtd.legend()
ax_lucro.legend(loc='upper center')
fig.show()

### **Multiplos gráficos em 1 figura**

In [ ]:
# Dados para plots
quarters = ['Q1/2019', 'Q2/2019', 'Q3/2019', 'Q4/2019']
vendas_pcs = [10, 13, 11, 16]
vendas_laptops = [24, 23, 27, 32]
vendas_video_games = [8, 6, 7, 10]
products = ['PCs', 'Laptops', 'Video Games']
vendas = [10, 24, 8]
bottom_2 = [a+b for a,b in zip(vendas_pcs, vendas_laptops)]
lucro = [3715.76, 3910.23, 4407.53, 6131.59]
largura = 0.5

# Gerando barras
fig, axs = plt.subplots(2, 2) # 2 linha e 2 colunas

# Quando temos linhas > 1 e colunas > 1, acessamos como uma matriz [x][y]
axs[0][0].bar(x=quarters, height=vendas_pcs, width=largura, label='PCs')
axs[0][0].bar(x=quarters, height=vendas_laptops, width=largura, bottom=vendas_pcs, label='Laptops')
axs[0][0].bar(x=quarters, height=vendas_video_games, width=largura, bottom=bottom_2, label='Video Games')

axs[0][0].set_xlabel('Quarter')
axs[0][0].set_ylabel('Venda Total')
axs[0][0].set_title('Vendas por Quarter e Produto')
axs[0][0].legend()

# Gerando linha
# Gerando novo eixo y com o mesmo x
axs[0][1].plot(quarters, lucro, '--om', label='Lucro', linewidth=4, markersize=8)
axs[0][1].set_ylabel('Lucro Total')
axs[0][1].set_ylim(0, 7000)
axs[0][1].set_title('Lucro')
axs[0][1].legend()

# Gerando pizza
axs[1][0].pie(vendas, labels=products, autopct='%.2f%%', shadow=True)
axs[1][0].set_title('Proporção de venda de produtos')

# Aumentando o tamanho da figura para não distorcer os gráficos
fig.set_figwidth(12)
fig.set_figheight(6)

fig.tight_layout() # Adiciona um padding entre os gráficos automaticamente

fig.show()

## **Exercício #6**

Construa um gráfico de linhas contendo as vendas de PCs, Laptops e vídeo games no gráfico em branco.

In [ ]:
# Modifique o código abaixo
# Dados para plots
quarters = ['Q1/2019', 'Q2/2019', 'Q3/2019', 'Q4/2019']
vendas_pcs = [10, 13, 11, 16]
vendas_laptops = [24, 23, 27, 32]
vendas_video_games = [8, 6, 7, 10]
products = ['PCs', 'Laptops', 'Video Games']
vendas = [10, 24, 8]
bottom_2 = [a+b for a,b in zip(vendas_pcs, vendas_laptops)]
lucro = [3715.76, 3910.23, 4407.53, 6131.59]
largura = 0.5

# Gerando barras
fig, axs = plt.subplots(2, 2) # 2 linha e 2 colunas

# Quando temos linhas > 1 e colunas > 1, acessamos como uma matriz [x][y]
axs[0][0].bar(x=quarters, height=vendas_pcs, width=largura, label='PCs')
axs[0][0].bar(x=quarters, height=vendas_laptops, width=largura, bottom=vendas_pcs, label='Laptops')
axs[0][0].bar(x=quarters, height=vendas_video_games, width=largura, bottom=bottom_2, label='Video Games')

axs[0][0].set_xlabel('Quarter')
axs[0][0].set_ylabel('Venda Total')
axs[0][0].set_title('Vendas por Quarter e Produto')
axs[0][0].legend()

# Gerando linha
# Gerando novo eixo y com o mesmo x
axs[0][1].plot(quarters, lucro, '--om', label='Lucro', linewidth=4, markersize=8)
axs[0][1].set_ylabel('Lucro Total (R$)')
axs[0][1].set_ylim(0, 7000)
axs[0][1].set_title('Lucro')
axs[0][1].legend()

# Gerando pizza
axs[1][0].pie(vendas, labels=products, autopct='%.2f%%', shadow=True)
axs[1][0].set_title('Proporção de venda de produtos')

# Novo gráfico
# TODO
# axs[1][1]...

# Aumentando o tamanho da figura para não distorcer os gráficos
fig.set_figwidth(12)
fig.set_figheight(6)

fig.tight_layout() # Adiciona um padding entre os gráficos automaticamente

fig.show()

In [ ]:
#@title Resposta

# Dados para plots
quarters = ['Q1/2019', 'Q2/2019', 'Q3/2019', 'Q4/2019']
vendas_pcs = [10, 13, 11, 16]
vendas_laptops = [24, 23, 27, 32]
vendas_video_games = [8, 6, 7, 10]
products = ['PCs', 'Laptops', 'Video Games']
vendas = [10, 24, 8]
bottom_2 = [a+b for a,b in zip(vendas_pcs, vendas_laptops)]
lucro = [3715.76, 3910.23, 4407.53, 6131.59]
largura = 0.5

# Gerando barras
fig, axs = plt.subplots(2, 2) # 2 linha e 2 colunas

# Quando temos linhas > 1 e colunas > 1, acessamos como uma matriz [x][y]
axs[0][0].bar(x=quarters, height=vendas_pcs, width=largura, label='PCs')
axs[0][0].bar(x=quarters, height=vendas_laptops, width=largura, bottom=vendas_pcs, label='Laptops')
axs[0][0].bar(x=quarters, height=vendas_video_games, width=largura, bottom=bottom_2, label='Video Games')

axs[0][0].set_xlabel('Quarter')
axs[0][0].set_ylabel('Venda Total')
axs[0][0].set_title('Vendas por Quarter e Produto')
axs[0][0].legend()

# Gerando linha
# Gerando novo eixo y com o mesmo x
axs[0][1].plot(quarters, lucro, '--om', label='Lucro', linewidth=4, markersize=8)
axs[0][1].set_ylabel('Lucro Total')
axs[0][1].set_ylim(0, 7000)
axs[0][1].set_title('Lucro (R$)')
axs[0][1].legend()

# Gerando pizza
axs[1][0].pie(vendas, labels=products, autopct='%.2f%%', shadow=True)
axs[1][0].set_title('Proporção de venda de produtos')

# Novo gráfico
axs[1][1].plot(quarters, vendas_pcs, '-o', label='PCs', linewidth=4, markersize=8)
axs[1][1].plot(quarters, vendas_laptops, '-+', label='Laptops',linewidth=4, markersize=12)
axs[1][1].plot(quarters, vendas_video_games, '-8', label='Video Games', linewidth=4, markersize=8)
axs[1][1].set_ylabel('Unidades Vendidas')
axs[1][1].set_title('Evolução de Vendas')
axs[1][1].legend(loc='upper left')

# Aumentando o tamanho da figura para não distorcer os gráficos
fig.set_figwidth(12)
fig.set_figheight(6)

fig.tight_layout() # Adiciona um padding entre os gráficos automaticamente

fig.show()

# **Pandas + Matplotlib**

O Pandas utiliza o Matplotlib para facilitar a visualização de seus DataFrames, a seguir vamos investigar um pouco essa integração.

[API](https://pandas.pydata.org/docs/reference/frame.html#plotting)

In [ ]:
# Carregando os dados
import pandas as pd
from google.colab import auth
import gspread
from oauth2client.client import GoogleCredentials
auth.authenticate_user()

GAMES_SALES_DATASET_URL = 'https://docs.google.com/spreadsheets/d/1Bq5IxppilddbsQ0aVAToRkVdeQ0i9KlEsWPLq-fCaQg/edit?usp=sharing'

gc = gspread.authorize(GoogleCredentials.get_application_default())
worksheet = gc.open_by_url(GAMES_SALES_DATASET_URL).sheet1
rows = worksheet.get_all_values()

g_sales_df = pd.DataFrame.from_records(columns=rows[0], data=rows[1:])
g_sales_df['Name'] = g_sales_df['Name'].astype('category')
g_sales_df['Platform'] = g_sales_df['Platform'].astype('category')
g_sales_df['Year'] = g_sales_df['Year'].astype('category')
g_sales_df['Genre'] = g_sales_df['Genre'].astype('category')
g_sales_df['Publisher'] = g_sales_df['Publisher'].astype('category')
g_sales_df['NA_Sales'] = g_sales_df['NA_Sales'].astype('float')
g_sales_df['EU_Sales'] = g_sales_df['EU_Sales'].astype('float')
g_sales_df['JP_Sales'] = g_sales_df['JP_Sales'].astype('float')
g_sales_df['Other_Sales'] = g_sales_df['Other_Sales'].astype('float')
g_sales_df['Global_Sales'] = g_sales_df['Global_Sales'].astype('float')
g_sales_df.head()

A função plot() do DataFrame faz um plot básico de todas as séries numéricas.

In [ ]:
g_sales_df.plot()

Vamos trabalhar um pouco os dados para melhorar a visualização.

In [ ]:
# Deixando apenas linhas com o valor dos anos
g_sales_df = g_sales_df[g_sales_df['Year'] != 'N/A']
g_sales_df['Year'] = g_sales_df['Year'].astype('int')

# Ordernando pelo ano
g_sales_df = g_sales_df.sort_values(by='Year')

# Tornando a coluna 'Year' como indice
indexed_df = g_sales_df.set_index('Year')

# Removendo coluna Rank
indexed_df = indexed_df.drop(columns='Rank')

indexed_df.head()

In [ ]:
# Soma de vendas por ano
indexed_df.groupby(by=['Year']).sum().plot()

In [ ]:
# Soma de vendas por genero
indexed_df.groupby(by=['Genre']).sum().plot.area()

In [ ]:
# Média de vendas por plataforma
indexed_df.groupby(by=['Platform']).mean().plot.bar(figsize=(20, 5))

In [ ]:
# Relação de vendas entre Plataforma e Genero
indexed_df.plot.scatter(x='Platform', y='Genre', figsize=(20, 5), s='Global_Sales')

In [ ]:
# Relação de vendas entre North America e Europa
indexed_df.plot.scatter(x='NA_Sales', y='EU_Sales', figsize=(6, 6), s='Global_Sales', xlim=(0, 40), ylim=(0,40))

# **Material complementar**

**Meus contatos**

e-mail: rjanuzi@gmail.com

Linkedin: [https://www.linkedin.com/in/rafael-januzi-4b208118a/](https://www.linkedin.com/in/rafael-januzi-4b208118a/)


**Sugestões para estudo**

[Guia básico de utilização](https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py)

[Tutorial Oficial](https://matplotlib.org/tutorials/index.html)

[Galeria](https://matplotlib.org/3.3.2/gallery/index.html)

[API](https://pandas.pydata.org/docs/reference/index.html)

[Github](https://github.com/matplotlib/matplotlib)

**Bibliotecas Relacionadas**

[Seaborn](https://seaborn.pydata.org/)

[Plotly](https://plotly.com/python/)

[Outras](https://matplotlib.org/thirdpartypackages/index.html)
